# File system
alias ls='eza -lh --group-directories-first --icons'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'
alias fuz="fzf --preview 'bat --style=numbers --color=always {}'"
alias fd='fdfind'
alias zshconfig="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias swayconfig="nvim ~/.config/sway/config"
alias zel="zellij"
alias zela="zellij a"
alias mongs="sudo systemctl start mongod"
alias mongx="sudo systemctl stop mongod"
alias Pdoc="cd ~/Doc/Portfolio/"
alias posh="pwsh"
alias deb="ssh 192.168.1.22"
alias pn="pnpm"
alias pni="pnpm install"
alias pnu="pnpm update"
alias pns="pnpm start"
alias pnt="pnpm test"
alias pnb="pnpm build"
alias pnr="pnpm run"
alias pnl="pnpm list"
alias dlx="pnpm dlx"
alias ff="pokeget gengar --hide-name | fastfetch --file-raw -"
alias fz="fzf --preview 'bat --color=always {}'"
# alias cd='~'

# Directories
# alias ..='cd ..'
# alias ...='cd ../..'
# alias ....='cd ../../..'

# Tools
alias n='nvim'
alias e='emacsclient -c -a emacs'
alias g='git'
alias d='docker'
alias r='rails'
# alias bat='batcat'
alias lzg='lazygit'
alias lzd='lazydocker'

# Git
alias gcm='git commit -m'
alias gcam='git commit -a -m'
alias gcad='git commit -a --amend'

# Compression
compress() { tar -czf "${1%/}.tar.gz" "${1%/}"; }
alias decompress="tar -xzf"

# Convert webm files generated by the Gnome screenshot video recorder to mp4s that are more compatible
webm2mp4() {
  input_file="$1"
  output_file="${input_file%.webm}.mp4"
  ffmpeg -i "$input_file" -c:v libx264 -preset slow -crf 22 -c:a aac -b:a 192k "$output_file"
}

#misc
alias vterm='emacs --eval "(vterm)"'
alias ipy="ipython"
alias of="onefetch"
alias rpi="kitten ssh legendairy@192.168.1.46"
alias info='info --vi-keys'
