# File system
# alias ls='eza -lh --group-directories-first --icons'
alias ls='nu -c "ls -l"'
alias la='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'
alias fd='fdfind'
alias zshconfig="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias pn="pnpm"
alias pni="pnpm install"
alias pnu="pnpm update"
alias pns="pnpm start"
alias pnt="pnpm test"
alias pnb="pnpm build"
alias pnr="pnpm run"
alias pnl="pnpm list"
alias dlx="pnpm dlx"
alias ff="pokeget gengar --hide-name | fastfetch --file-raw -"
alias fz="fzf --preview 'bat --color=always {}'"

# Tools
alias n='nvim'
alias v="vim"
alias e='emacsclient -c -a emacs'
alias d='docker'
alias lzg='lazygit'
alias lzd='lazydocker'

# Git
alias g='git'
alias gc='git commit -m'
alias gca='git commit -a -m'
alias gcad='git commit -a --amend'
alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gst="git stash"
alias gsp="git stash; git pull"
alias gfo="git fetch origin"
alias gcheck="git checkout"
alias gcredential="git config credential.helper store"

# Compression
compress() { tar -czf "${1%/}.tar.gz" "${1%/}"; }
alias decompress="tar -xzf"

# Convert webm files generated by the Gnome screenshot video recorder to mp4s that are more compatible

#misc
alias vterm='emacs --eval "(vterm)"'
alias ipy="ipython"
alias of="onefetch"
alias info='info --vi-keys'

#ml4w
alias wifi='nmtui'
alias apps='~/.config/ml4w/bin/ml4w-apps.sh'
alias screenshot='~/.config/ml4w/bin/ml4w-screenshot.sh'
alias updates='~/.config/ml4w/scripts/installupdates.sh'
alias lock='hyprlock'
alias quick='~/.config/ml4w/bin/ml4w-quicklinks.sh'
alias wallpaper='~/.config/ml4w/bin/ml4w-wallpaper.sh'

# -----------------------------------------------------
# ML4W Apps
# -----------------------------------------------------
alias ml4w='flatpak run com.ml4w.welcome'
alias ml4w-settings='flatpak run com.ml4w.settings'
alias ml4w-calendar='flatpak run com.ml4w.calendar'
alias ml4w-hyprland='flatpak run com.ml4w.hyprlandsettings'
alias ml4w-sidebar='flatpak run com.ml4w.sidebar'

# -----------------------------------------------------
# Scripts
# -----------------------------------------------------
alias ascii='~/.config/ml4w/scripts/figlet.sh'

# -----------------------------------------------------
# System
# -----------------------------------------------------
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'

#bash

alias shutdown='systemctl poweroff'
alias wifi='nmtui'
alias arch-cleanup='~/.config/ml4w/scripts/arch/cleanup.sh'
alias apps='~/.config/ml4w/bin/ml4w-apps.sh'
alias screenshot='~/.config/ml4w/bin/ml4w-screenshot.sh'
alias updates='~/.config/ml4w/scripts/installupdates.sh'
alias filemanager='~/.config/ml4w/settings/filemanager'
alias lock='hyprlock'
alias clock='tty-clock'
alias system='~/.config/ml4w/settings/systemmonitor'
alias quick='~/.config/ml4w/bin/ml4w-quicklinks.sh'
alias wallpaper='~/.config/ml4w/bin/ml4w-wallpaper.sh'

# -----------------------------------------------------
# ML4W Apps
# -----------------------------------------------------
alias ml4w='flatpak run com.ml4w.welcome'
alias ml4w-settings='flatpak run com.ml4w.settings'
alias ml4w-calendar='flatpak run com.ml4w.calendar'
alias ml4w-hyprland='flatpak run com.ml4w.hyprlandsettings'
alias ml4w-sidebar='flatpak run com.ml4w.sidebar'

# -----------------------------------------------------
# Scripts
# -----------------------------------------------------
alias ascii='~/.config/ml4w/scripts/figlet.sh'

# -----------------------------------------------------
# System
# -----------------------------------------------------
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
