 font_family      MesloLGM Nerd Font
 bold_font        auto
 italic_font      auto
 bold_italic_font auto

include current-theme.conf

dynamic_background_opacity yes

# map ctrl+shift+z scroll_to_prompt -1
# map ctrl+shift+x scroll_to_prompt 1
# map ctrl+shift+h show_scrollback
